# Generated by Django 4.0.6 on 2022-07-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_noticia_comentario'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='noticias.noticia'),
        ),
    ]
