# Generated by Django 4.0.6 on 2022-07-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentario')),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
    ]
